# -*- coding: utf-8 -*-
"""AI_23.6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11gwAt8RIpPLr1lxiR34fH7_rE63BLm7x
"""

!pip install -q osmnx folium geopandas networkx pandas

import osmnx as ox
import networkx as nx
import pandas as pd
import folium
from IPython.display import display

CENTER = (10.761000, 106.668472)
center_name = "QM69+95 Diên Hồng, Hồ Chí Minh, Việt Nam"

ox.settings.use_cache = True
ox.settings.log_console = False

G = ox.graph_from_point(
    CENTER,
    dist=1500,
    network_type="drive",
    simplify=True
)

print("Đã tải xong mạng lưới giao thông.")
print(type(G))

nodes, edges = ox.graph_to_gdfs(G)

so_nut_giao = len(nodes)
so_doan_duong = len(edges)
tong_chieu_dai_m = edges["length"].sum()
chieu_dai_trung_binh_m = edges["length"].mean()

stats = ox.stats.basic_stats(G)

summary = pd.DataFrame({
    "Chỉ số": [
        "Số nút giao",
        "Số đoạn đường",
        "Tổng chiều dài đường (m)",
        "Chiều dài đường trung bình (m)",
        "Bậc trung bình của nút"
    ],
    "Giá trị": [
        so_nut_giao,
        so_doan_duong,
        round(tong_chieu_dai_m, 2),
        round(chieu_dai_trung_binh_m, 2),
        round(stats["k_avg"], 2)
    ]
})

display(summary)

m = folium.Map(
    location=[CENTER[0], CENTER[1]],
    zoom_start=15,
    tiles="OpenStreetMap"
)

folium.TileLayer("CartoDB positron", name="Bản đồ sáng").add_to(m)

folium.Marker(
    location=[CENTER[0], CENTER[1]],
    popup=f"""
    <b>Mốc trung tâm</b><br>
    {center_name}<br>
    Vĩ độ: {CENTER[0]}<br>
    Kinh độ: {CENTER[1]}
    """,
    tooltip="Mốc trung tâm",
    icon=folium.Icon(color="red", icon="home")
).add_to(m)

road_layer = folium.FeatureGroup(name="Mạng lưới giao thông đường bộ")

for _, row in edges.iterrows():
    if row.geometry is not None:
        coords = [(lat, lon) for lon, lat in row.geometry.coords]

        folium.PolyLine(
            locations=coords,
            color="blue",
            weight=2,
            opacity=0.7
        ).add_to(road_layer)

road_layer.add_to(m)

folium.Circle(
    location=[CENTER[0], CENTER[1]],
    radius=1500,
    color="red",
    fill=False,
    popup="Khu vực tải mạng đường bán kính 1.5 km"
).add_to(m)

folium.LayerControl(collapsed=False).add_to(m)

display(m)

"""Nhận xét:
Mạng lưới giao thông trong khu vực có khả năng kết nối tương đối tốt vì xuất hiện nhiều nút giao và nhiều đoạn đường liên kết với nhau. Điều này tạo ra nhiều lựa chọn tuyến đường cho việc di chuyển. Khi một tuyến đường bị ùn tắc hoặc không thuận tiện, hệ thống có thể lựa chọn tuyến đường thay thế. Tuy nhiên, việc có nhiều nút giao và đoạn đường cũng làm cho bài toán định tuyến trở nên phức tạp hơn, vì hệ thống phải xử lý nhiều khả năng di chuyển khác nhau.

**Về ý nghĩa trong hệ thống định tuyến thông minh**, dữ liệu mạng giao thông giúp xác định các tuyến đường khả thi, tính toán đường đi ngắn nhất, ước lượng khoảng cách và hỗ trợ điều phối phương tiện. Đây là nền tảng quan trọng cho các bài toán như giao hàng, gọi xe công nghệ, tìm đường đi tối ưu và quản lý vận tải đô thị. Từ mạng lưới này, có thể tiếp tục áp dụng các thuật toán như Dijkstra hoặc A để tìm tuyến đường phù hợp nhất giữa hai địa điểm.
"""