# -*- coding: utf-8 -*-
"""AI_23.5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ev_eINkb-yqDUOoAhfoec--G7cPvKMXZ

23.5. Bạn hãy xây dựng mô hình phân tích vùng phục vụ, service area, cho một trung tâm phân phối, kho hàng hoặc trạm dịch vụ. Sử dụng dữ liệu tọa độ để vẽ các vòng bán kính phục vụ khác nhau, ví dụ: 3 km, 5 km và 10 km, và trực quan hóa trên bản đồ. Bài làm cần đánh giá khả năng tiếp cận khách hàng trong từng vùng và đề xuất phạm vi hoạt động tối ưu.
"""

!pip install -q folium geopy pandas

import folium
import pandas as pd
from geopy.distance import geodesic
from IPython.display import display

CENTER = [10.761000, 106.668472]
center_name = "Trung tâm phục vụ - QM69+95 Diên Hồng, Hồ Chí Minh"

customers = [
    {
        "name": "Sân vận động Thống Nhất",
        "lat": 10.760780618320489,
        "lon": 106.6633034911617
    },
    {
        "name": "Co.opmart Lý Thường Kiệt",
        "lat": 10.759911238502184,
        "lon": 106.66141579438909
    },
    {
        "name": "Bệnh viện Nhi Đồng 1",
        "lat": 10.768686799824161,
        "lon": 106.67013632394121
    },
    {
        "name": "Đại học Y Dược TP.HCM",
        "lat": 10.755311007461684,
        "lon": 106.66289975728797
    },
    {
        "name": "Sân vận động Phú Thọ",
        "lat": 10.767608919048195,
        "lon": 106.65589171857464
    },
    {
        "name": "Công viên Lê Thị Riêng",
        "lat": 10.78517332524066,
        "lon": 106.66473124284278
    },
    {
        "name": "Bảo tàng chứng tích chiến tranh",
        "lat": 10.779522316877387,
        "lon": 106.69209861012955
    },
    {
        "name": "Dinh Độc Lập",
        "lat": 10.776998896589069,
        "lon": 106.69525140573835
    },
    {
        "name": "Nhà hát Thành phố Hồ Chí Minh",
        "lat": 10.77663293266581,
        "lon": 106.70317741906521
    },
    {
        "name": "Bến xe Miền Tây",
        "lat": 10.7401,
        "lon": 106.6183
    },
    {
        "name": "Landmark 81",
        "lat": 10.7942,
        "lon": 106.7214
    },
    {
        "name": "Aeon Mall Tân Phú",
        "lat": 10.8015,
        "lon": 106.6180
    }
]

results = []

for customer in customers:
    distance_km = geodesic(
        (CENTER[0], CENTER[1]),
        (customer["lat"], customer["lon"])
    ).km

    if distance_km <= 3:
        service_zone = "Vùng 1 - phục vụ rất tốt trong 3 km"
        color = "green"
    elif distance_km <= 5:
        service_zone = "Vùng 2 - phục vụ tốt trong 5 km"
        color = "blue"
    elif distance_km <= 10:
        service_zone = "Vùng 3 - phục vụ mở rộng trong 10 km"
        color = "orange"
    else:
        service_zone = "Ngoài vùng phục vụ chính"
        color = "red"

    results.append({
        "Tên điểm": customer["name"],
        "Vĩ độ": customer["lat"],
        "Kinh độ": customer["lon"],
        "Khoảng cách đến trung tâm (km)": round(distance_km, 2),
        "Vùng phục vụ": service_zone,
        "Màu": color
    })

df = pd.DataFrame(results)
df = df.sort_values(by="Khoảng cách đến trung tâm (km)")
display(df)

summary = df["Vùng phục vụ"].value_counts().reset_index()
summary.columns = ["Vùng phục vụ", "Số lượng điểm"]
display(summary)

m = folium.Map(
    location=CENTER,
    zoom_start=13,
    tiles="OpenStreetMap"
)

folium.TileLayer("CartoDB positron", name="Bản đồ sáng").add_to(m)
folium.TileLayer("CartoDB dark_matter", name="Bản đồ tối").add_to(m)

folium.Marker(
    location=CENTER,
    popup=f"""
    <b>{center_name}</b><br>
    Vĩ độ: {CENTER[0]}<br>
    Kinh độ: {CENTER[1]}
    """,
    tooltip="Trung tâm phục vụ",
    icon=folium.Icon(color="red", icon="home")
).add_to(m)

folium.Circle(
    location=CENTER,
    radius=3000,
    color="green",
    fill=True,
    fill_opacity=0.08,
    popup="Vùng phục vụ 3 km"
).add_to(m)

folium.Circle(
    location=CENTER,
    radius=5000,
    color="blue",
    fill=True,
    fill_opacity=0.06,
    popup="Vùng phục vụ 5 km"
).add_to(m)

folium.Circle(
    location=CENTER,
    radius=10000,
    color="orange",
    fill=True,
    fill_opacity=0.04,
    popup="Vùng phục vụ 10 km"
).add_to(m)

for _, row in df.iterrows():
    point = [row["Vĩ độ"], row["Kinh độ"]]

    popup_text = f"""
    <b>{row['Tên điểm']}</b><br>
    Khoảng cách đến trung tâm: {row['Khoảng cách đến trung tâm (km)']} km<br>
    Vùng phục vụ: {row['Vùng phục vụ']}
    """

    folium.Marker(
        location=point,
        popup=popup_text,
        tooltip=row["Tên điểm"],
        icon=folium.Icon(color=row["Màu"], icon="info-sign")
    ).add_to(m)

    folium.PolyLine(
        locations=[
            [CENTER[0], CENTER[1]],
            point
        ],
        color=row["Màu"],
        weight=2,
        opacity=0.6
    ).add_to(m)

folium.LayerControl(collapsed=False).add_to(m)

display(m)

"""Nhận xét :

Các điểm nằm trong bán kính 3 km được xem là vùng phục vụ rất tốt vì khoảng cách gần, thời gian di chuyển ngắn và chi phí vận hành thấp. Các điểm trong bán kính 5 km vẫn có khả năng phục vụ tốt, phù hợp cho giao hàng hoặc hỗ trợ khách hàng trong thời gian hợp lý. Các điểm trong bán kính 10 km thuộc vùng phục vụ mở rộng, có thể tiếp cận nhưng cần nhiều thời gian và chi phí hơn.

Về đề xuất quản trị, phạm vi hoạt động tối ưu nên ưu tiên trong bán kính 5 km quanh trung tâm vì đây là vùng cân bằng giữa khả năng tiếp cận khách hàng, thời gian di chuyển và chi phí vận hành. Vùng 10 km có thể được sử dụng khi nhu cầu tăng cao hoặc khi cần mở rộng thị trường, nhưng nên cân nhắc thêm điểm trung chuyển để giảm chi phí và thời gian phục vụ.
"""