# -*- coding: utf-8 -*-
"""AI_23.7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/102q4v3PitEQbBsvPwUGATvOL0PpJFUlO

23.7. Kết hợp OSMnx và NetworkX, bạn hãy xây dựng chương trình tìm đường đi ngắn nhất giữa hai địa điểm bất kỳ trong khu vực nghiên cứu. So sánh kết quả giữa ít nhất hai thuật toán, ví dụ: Dijkstra và A*. Tuyến đường tìm được cần được hiển thị trực quan trên bản đồ và phân tích ưu, nhược điểm của từng phương pháp.
"""

!pip install -q osmnx networkx folium geopy pandas

import osmnx as ox
import networkx as nx
import folium
import pandas as pd
import time
from geopy.distance import geodesic
from IPython.display import display

start_point = (10.761000, 106.668472)
start_name = "QM69+95 Diên Hồng, Hồ Chí Minh"

end_point = (10.768686799824161, 106.67013632394121)
end_name = "Bệnh viện Nhi Đồng 1"

ox.settings.use_cache = True
ox.settings.log_console = False

G = ox.graph_from_point(
    start_point,
    dist=3000,
    network_type="drive",
    simplify=True
)

print("Đã tải xong mạng lưới giao thông.")
print("Số nút giao:", len(G.nodes))
print("Số đoạn đường:", len(G.edges))

start_node = ox.distance.nearest_nodes(
    G,
    X=start_point[1],
    Y=start_point[0]
)

end_node = ox.distance.nearest_nodes(
    G,
    X=end_point[1],
    Y=end_point[0]
)

print("Start node:", start_node)
print("End node:", end_node)

def calculate_route_length(G, route):
    total_length = 0

    for u, v in zip(route[:-1], route[1:]):
        edge_data = G.get_edge_data(u, v)
        min_length = min(data["length"] for data in edge_data.values())
        total_length += min_length

    return total_length

start_time = time.perf_counter()

route_dijkstra = nx.shortest_path(
    G,
    source=start_node,
    target=end_node,
    weight="length",
    method="dijkstra"
)

dijkstra_time = time.perf_counter() - start_time
dijkstra_length = calculate_route_length(G, route_dijkstra)

print("Dijkstra:")
print("Chiều dài tuyến đường:", round(dijkstra_length, 2), "m")
print("Thời gian xử lý:", round(dijkstra_time, 6), "giây")

def heuristic(node1, node2):
    lat1 = G.nodes[node1]["y"]
    lon1 = G.nodes[node1]["x"]

    lat2 = G.nodes[node2]["y"]
    lon2 = G.nodes[node2]["x"]

    return geodesic((lat1, lon1), (lat2, lon2)).meters


start_time = time.perf_counter()

route_astar = nx.astar_path(
    G,
    source=start_node,
    target=end_node,
    heuristic=heuristic,
    weight="length"
)

astar_time = time.perf_counter() - start_time
astar_length = calculate_route_length(G, route_astar)

print("A*:")
print("Chiều dài tuyến đường:", round(astar_length, 2), "m")
print("Thời gian xử lý:", round(astar_time, 6), "giây")

comparison = pd.DataFrame({
    "Thuật toán": ["Dijkstra", "A*"],
    "Chiều dài tuyến đường (m)": [
        round(dijkstra_length, 2),
        round(astar_length, 2)
    ],
    "Chiều dài tuyến đường (km)": [
        round(dijkstra_length / 1000, 3),
        round(astar_length / 1000, 3)
    ],
    "Thời gian xử lý (giây)": [
        round(dijkstra_time, 6),
        round(astar_time, 6)
    ],
    "Số node trên tuyến": [
        len(route_dijkstra),
        len(route_astar)
    ]
})

display(comparison)

def get_route_coordinates(G, route):
    coords = []

    for node in route:
        lat = G.nodes[node]["y"]
        lon = G.nodes[node]["x"]
        coords.append((lat, lon))

    return coords


dijkstra_coords = get_route_coordinates(G, route_dijkstra)
astar_coords = get_route_coordinates(G, route_astar)

m = folium.Map(
    location=start_point,
    zoom_start=15,
    tiles="OpenStreetMap"
)

folium.TileLayer("CartoDB positron", name="Bản đồ sáng").add_to(m)

folium.Marker(
    location=start_point,
    popup=f"""
    <b>Điểm bắt đầu</b><br>
    {start_name}<br>
    Vĩ độ: {start_point[0]}<br>
    Kinh độ: {start_point[1]}
    """,
    tooltip="Điểm bắt đầu",
    icon=folium.Icon(color="green", icon="play")
).add_to(m)

folium.Marker(
    location=end_point,
    popup=f"""
    <b>Điểm kết thúc</b><br>
    {end_name}<br>
    Vĩ độ: {end_point[0]}<br>
    Kinh độ: {end_point[1]}
    """,
    tooltip="Điểm kết thúc",
    icon=folium.Icon(color="red", icon="stop")
).add_to(m)

folium.PolyLine(
    locations=dijkstra_coords,
    color="blue",
    weight=6,
    opacity=0.8,
    popup=f"Dijkstra - {round(dijkstra_length / 1000, 3)} km"
).add_to(m)

folium.PolyLine(
    locations=astar_coords,
    color="orange",
    weight=4,
    opacity=0.8,
    dash_array="10",
    popup=f"A* - {round(astar_length / 1000, 3)} km"
).add_to(m)

folium.Circle(
    location=start_point,
    radius=3000,
    color="red",
    fill=False,
    popup="Phạm vi tải mạng đường 3 km"
).add_to(m)

folium.LayerControl(collapsed=False).add_to(m)

display(m)

"""Nhận xét :
Hai thuật toán được áp dụng là Dijkstra và A*

Thuật toán Dijkstra tìm đường ngắn nhất bằng cách mở rộng dần từ điểm bắt đầu và xét các tuyến có tổng chiều dài nhỏ nhất. Thuật toán A* cũng tìm đường ngắn nhất nhưng sử dụng thêm hàm heuristic, trong bài này là khoảng cách đường chim bay giữa các node, để định hướng quá trình tìm kiếm về phía điểm đích. Vì vậy, A* thường có khả năng xử lý nhanh hơn trong các mạng đường lớn.

Kết quả tuyến đường được hiển thị trực quan trên bản đồ Folium. Tuyến Dijkstra được biểu diễn bằng đường màu xanh, còn tuyến A* được biểu diễn bằng đường màu cam nét đứt. Nếu hai tuyến trùng hoặc gần trùng nhau, điều này cho thấy cả hai thuật toán đều tìm được tuyến tối ưu tương tự khi cùng sử dụng trọng số là chiều dài đường.

Về ưu điểm, Dijkstra dễ hiểu, ổn định và đảm bảo tìm được đường ngắn nhất nếu dữ liệu đầy đủ. Tuy nhiên, thuật toán này có thể phải duyệt nhiều node nên tốn thời gian hơn trên mạng lớn. A* có ưu điểm là tìm kiếm có định hướng nhờ heuristic, nên thường nhanh hơn, nhưng chất lượng phụ thuộc vào hàm heuristic được chọn. Trong hệ thống định tuyến thông minh như giao hàng hoặc gọi xe, A* thường phù hợp hơn khi cần tìm đường nhanh trên mạng giao thông lớn.
"""