# -*- coding: utf-8 -*-
"""AI 23_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kSpc7-TRXCwBDFDVFJENKHPjDaIGlfuj

23.3. Bạn hãy tạo một bản đồ nhiệt, heatmap, thể hiện mật độ phân bố của một hiện tượng không gian như khách hàng, đơn hàng, dân cư hoặc điểm giao dịch, dữ liệu có thể giả lập. Bản đồ phải cho phép người xem nhận biết trực quan các khu vực có mật độ cao và thấp, đồng thời giải thích ý nghĩa quản trị của các vùng nóng trên bản đồ.
"""

!pip install -q folium pandas numpy

import pandas as pd
import folium
import numpy as np
from folium.plugins import HeatMap
from IPython.display import display

CENTER = [ 10.761000, 106.668472]
center_name = " QM69+95 Diên Hồng, Hồ Chí Minh, Việt Nam "

np.random.seed(42)

clusters = [
    {
        "name": "Khu vực Sân vận động Thống Nhất",
        "center": [10.760780618320489, 106.6633034911617],
        "n": 40
    },
    {
        "name": "Khu vực Bệnh viện Nhi Đồng 1",
        "center": [10.768686799824161, 106.67013632394121],
        "n": 35
    },
    {
        "name": "Khu vực Co.opmart Lý Thường Kiệt",
        "center": [10.759911238502184, 106.66141579438909],
        "n": 30
    },
    {
        "name": "Khu vực Đại học Y Dược TP.HCM",
        "center": [10.755311007461684, 106.66289975728797],
        "n": 25
    },
    {
        "name": "Khu vực Công viên Lê Thị Riêng",
        "center": [10.78517332524066, 106.66473124284278],
        "n": 20
    }
]

data = []

for cluster in clusters:
    for i in range(cluster["n"]):
        lat = np.random.normal(cluster["center"][0], 0.002)
        lon = np.random.normal(cluster["center"][1], 0.002)
        order_count = np.random.randint(1, 8)

        data.append({
            "Khu vực": cluster["name"],
            "Vĩ độ": lat,
            "Kinh độ": lon,
            "Số đơn hàng": order_count
        })

df = pd.DataFrame(data)
display(df.head())
summary = df.groupby("Khu vực")["Số đơn hàng"].sum().reset_index()
display(summary)

m = folium.Map(
    location=CENTER,
    zoom_start=14,
    tiles="OpenStreetMap"
)

folium.Marker(
    location=CENTER,
    popup=center_name,
    icon=folium.Icon(color="red", icon="home")
).add_to(m)

heat_data = df[["Vĩ độ", "Kinh độ", "Số đơn hàng"]].values.tolist()

HeatMap(
    heat_data,
    name="Bản đồ nhiệt mật độ đơn hàng",
    radius=22,
    blur=18
).add_to(m)

folium.Marker(
    location=cluster["center"],
    popup=cluster["name"],
    icon=folium.Icon(color="blue", icon="info-sign")
).add_to(m)

folium.Circle(
    location=CENTER,
    radius=1000,
    color="red",
    fill=True,
    fill_opacity=0.08,
    popup="Bán kính 1 km quanh mốc trung tâm"
).add_to(m)

folium.LayerControl(collapsed=False).add_to(m)

display(m)