# -*- coding: utf-8 -*-
"""AI_23.4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pWKsx26p654yKeNzmiv1SNzM-pHPAIDM
"""

!pip install -q geopandas shapely folium pandas

import geopandas as gpd
import pandas as pd
import folium
from shapely.geometry import Polygon
from IPython.display import display

CENTER = [10.761000, 106.668472]
center_name = "QM69+95 Diên Hồng, Hồ Chí Minh, Việt Nam"

polygons = [
    Polygon([
        (106.6580, 10.7560),
        (106.6660, 10.7560),
        (106.6660, 10.7640),
        (106.6580, 10.7640)
    ]),
    Polygon([
        (106.6660, 10.7560),
        (106.6740, 10.7560),
        (106.6740, 10.7640),
        (106.6660, 10.7640)
    ]),
    Polygon([
        (106.6580, 10.7640),
        (106.6660, 10.7640),
        (106.6660, 10.7720),
        (106.6580, 10.7720)
    ]),
    Polygon([
        (106.6660, 10.7640),
        (106.6740, 10.7640),
        (106.6740, 10.7720),
        (106.6660, 10.7720)
    ]),
    Polygon([
        (106.6740, 10.7560),
        (106.6820, 10.7560),
        (106.6820, 10.7640),
        (106.6740, 10.7640)
    ])
]

boundary_data = {
    "Khu vực": [
        "Khu vực Sân vận động Thống Nhất",
        "Khu vực Diên Hồng",
        "Khu vực Bệnh viện Nhi Đồng 1",
        "Khu vực Vạn Hạnh",
        "Khu vực Đại học Sư phạm"
    ],
    "geometry": polygons
}

gdf = gpd.GeoDataFrame(boundary_data, crs="EPSG:4326")

data_number = pd.DataFrame({
    "Khu vực": [
        "Khu vực Sân vận động Thống Nhất",
        "Khu vực Diên Hồng",
        "Khu vực Bệnh viện Nhi Đồng 1",
        "Khu vực Vạn Hạnh",
        "Khu vực Đại học Sư phạm"
    ],
    "Số đơn hàng": [180, 240, 210, 320, 150],
    "Doanh thu": [5400000, 7200000, 6300000, 9600000, 4500000]
})

merged_gdf = gdf.merge(data_number, on="Khu vực")

display(merged_gdf[["Khu vực", "Số đơn hàng", "Doanh thu"]])

m = folium.Map(
    location=CENTER,
    zoom_start=14,
    tiles="OpenStreetMap"
)

folium.TileLayer("CartoDB positron", name="Bản đồ sáng").add_to(m)

folium.Marker(
    location=CENTER,
    popup=f"""
    <b>Mốc trung tâm</b><br>
    {center_name}<br>
    Vĩ độ: {CENTER[0]}<br>
    Kinh độ: {CENTER[1]}
    """,
    tooltip="Mốc trung tâm",
    icon=folium.Icon(color="red", icon="home")
).add_to(m)

folium.Choropleth(
    geo_data=merged_gdf.to_json(),
    name="Bản đồ Choropleth số đơn hàng",
    data=merged_gdf,
    columns=["Khu vực", "Số đơn hàng"],
    key_on="feature.properties.Khu vực",
    fill_color="YlOrRd",
    fill_opacity=0.7,
    line_opacity=0.8,
    legend_name="Số đơn hàng theo khu vực"
).add_to(m)

folium.GeoJson(
    merged_gdf.to_json(),
    name="Thông tin khu vực",
    tooltip=folium.GeoJsonTooltip(
        fields=["Khu vực", "Số đơn hàng", "Doanh thu"],
        aliases=["Khu vực:", "Số đơn hàng:", "Doanh thu:"],
        localize=True
    )
).add_to(m)

folium.LayerControl(collapsed=False).add_to(m)

display(m)