# -*- coding: utf-8 -*-
"""AI.23.2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xOeN1wwcOefBKiA6VH44-hGJGjXKGh4L
"""

!pip install -q folium

!pip install folium geopy

import pandas as pd
import folium
from geopy.geocoders import Nominatim
from geopy.distance import geodesic
from IPython.display import display
import time

CENTER = (10.761000, 106.668472)
center_name = "QM69+95 Diên Hồng, Hồ Chí Minh, Việt Nam"

places = [{  "name": "Dinh Độc Lập ",
    "address": "QMGW+Q4 Bến Thành, Hồ Chí Minh, Việt Nam",
    "fallback": (10.776998896589069, 106.69525140573835)},

{   "name": "Bảo tàng chứng tích chiến tranh ",
    "address": "Phường 6, Quận 3, Hồ Chí Minh 700000, Việt Nam",
    "fallback":(10.779522316877387, 106.69209861012955)},

{   "name": "Nhà hát Thành phố Hồ Chí Minh",
    "address": "07 Công trường Lam Sơn, Sài Gòn, Hồ Chí Minh 700000, Việt Nam",
    "fallback":(10.77663293266581, 106.70317741906521)},

{   "name": "Bảo tàng Thành phố Hồ Chí Minh",
    "address": "QMGX+9V Sài Gòn, Hồ Chí Minh, Việt Nam",
    "fallback":(10.776034043622614, 106.69952288495192)},

{   "name": "Đại Học Y Dược Thành Phố Hồ Chí Minh (UMP)",
    "address": "217 Đ. Hồng Bàng, Phường 11, Chợ Lớn, Hồ Chí Minh 700000, Việt Nam",
    "fallback":(10.755311007461684, 106.66289975728797)},

{   "name": "Sân vận động Thống Nhất",
    "address": "138 Đ. Đào Duy Từ, Phường 6, Diên Hồng, Hồ Chí Minh, Việt Nam",
    "fallback":(10.760780618320489, 106.6633034911617)},

{   "name": "Sân vận động Phú Thọ ",
    "address": "221 Đ. Lý Thường Kiệt, Phường 9, Phú Thọ, Hồ Chí Minh, Việt Nam",
    "fallback":(10.767608919048195, 106.65589171857464)},

{   "name": "Công viên Lê Thị Riêng ",
    "address": "875 Cách Mạng Tháng Tám, Phường 15, Hòa Hưng, Hồ Chí Minh 700000, Việt Nam",
    "fallback":(10.78517332524066, 106.66473124284278)},

{   "name": "Bệnh viện Nhi Đồng 1 ",
    "address": "341, Sư Vạn Hạnh/532 Lý Thái Tổ, Vườn Lài, Hồ Chí Minh 70000, Việt Nam",
    "fallback":(10.768686799824161, 106.67013632394121)},

{   "name": "Co.opmart Lý Thường Kiệt",
    "address": "497 Hoà Hảo, Phường 7, Diên Hồng, Hồ Chí Minh, Việt Nam",
    "fallback":(10.759911238502184, 106.66141579438909)},
]

geolocator = Nominatim(user_agent="bt_23_2_geopy_folium")
results = []

for place in places:
    try:
        location = geolocator.geocode(place["address"], timeout=10)
    except:
        location = None

    if location:
        lat = location.latitude
        lon = location.longitude
        found_address = location.address
        source = "GeoPy"
    else:
        lat = place["fallback"][0]
        lon = place["fallback"][1]
        found_address = "Dùng tọa độ dự phòng"
        source = "Fallback"

    distance_km = geodesic(CENTER, (lat, lon)).km

    results.append({
        "Tên địa điểm": place["name"],
        "Địa chỉ tìm kiếm": place["address"],
        "Địa chỉ tìm được": found_address,
        "Vĩ độ": lat,
        "Kinh độ": lon,
        "Khoảng cách đến trung tâm (km)": round(distance_km, 2),
        "Nguồn tọa độ": source
    })

    time.sleep(1)

df = pd.DataFrame(results)
df = df.sort_values(by="Khoảng cách đến trung tâm (km)")
display(df)

m = folium.Map(
    location=[CENTER[0], CENTER[1]],
    zoom_start=14,
    tiles="OpenStreetMap"
)

folium.Marker(
    location=[CENTER[0], CENTER[1]],
    popup=f"""
    <b>Mốc trung tâm</b><br>
    {center_name}<br>
    Vĩ độ: {CENTER[0]}<br>
    Kinh độ: {CENTER[1]}
    """,
    tooltip="Mốc trung tâm",
    icon=folium.Icon(color="red", icon="home")
).add_to(m)

for _, row in df.iterrows():
    point = [row["Vĩ độ"], row["Kinh độ"]]

    popup_text = f"""
    <b>{row['Tên địa điểm']}</b><br>
    Địa chỉ: {row['Địa chỉ tìm được']}<br>
    Vĩ độ: {row['Vĩ độ']}<br>
    Kinh độ: {row['Kinh độ']}<br>
    Khoảng cách đến trung tâm: {row['Khoảng cách đến trung tâm (km)']} km<br>
    Nguồn tọa độ: {row['Nguồn tọa độ']}
    """

    folium.Marker(
        location=point,
        popup=popup_text,
        tooltip=row["Tên địa điểm"],
        icon=folium.Icon(color="blue", icon="info-sign")
    ).add_to(m)

    folium.PolyLine(
        locations=[
            [CENTER[0], CENTER[1]],
            point
        ],
        color="green",
        weight=2,
        opacity=0.7
    ).add_to(m)

folium.Circle(
    location=[CENTER[0], CENTER[1]],
    radius=1000,
    color="red",
    fill=True,
    fill_opacity=0.1,
    popup="Bán kính 1 km quanh mốc trung tâm" ).add_to(m)

folium.LayerControl().add_to(m)

display(m)