# -*- coding: utf-8 -*-
"""AI_23.8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dtm-Cc38njGVOJo8DrFQI8gmD9anUorC

23.8. Bạn hãy mô phỏng một hệ thống gọi xe công nghệ đơn giản. Trong đó, vị trí khách hàng và xe được biểu diễn bằng tọa độ trên bản đồ. Áp dụng một phương pháp AI hoặc heuristic để gán xe phù hợp nhất cho từng khách hàng dựa trên khoảng cách hoặc thời gian di chuyển. Toàn bộ quá trình ghép xe và khách cần được trực quan hóa trên bản đồ.
"""

!pip install -q folium geopy pandas

import folium
import pandas as pd
from geopy.distance import geodesic
from IPython.display import display

CENTER = [10.761000, 106.668472]
center_name = "QM69+95 Diên Hồng, Hồ Chí Minh, Việt Nam"

customers = [
    {
        "customer_id": "KH01",
        "name": "Khách 1 - Gần Sân vận động Thống Nhất",
        "lat": 10.760780618320489,
        "lon": 106.6633034911617
    },
    {
        "customer_id": "KH02",
        "name": "Khách 2 - Gần Bệnh viện Nhi Đồng 1",
        "lat": 10.768686799824161,
        "lon": 106.67013632394121
    },
    {
        "customer_id": "KH03",
        "name": "Khách 3 - Gần Co.opmart Lý Thường Kiệt",
        "lat": 10.759911238502184,
        "lon": 106.66141579438909
    },
    {
        "customer_id": "KH04",
        "name": "Khách 4 - Gần Đại học Y Dược TP.HCM",
        "lat": 10.755311007461684,
        "lon": 106.66289975728797
    },
    {
        "customer_id": "KH05",
        "name": "Khách 5 - Gần Sân vận động Phú Thọ",
        "lat": 10.767608919048195,
        "lon": 106.65589171857464
    }
]

drivers = [
    {
        "driver_id": "XE01",
        "name": "Xe 1",
        "lat": 10.7615,
        "lon": 106.6660
    },
    {
        "driver_id": "XE02",
        "name": "Xe 2",
        "lat": 10.7665,
        "lon": 106.6710
    },
    {
        "driver_id": "XE03",
        "name": "Xe 3",
        "lat": 10.7580,
        "lon": 106.6600
    },
    {
        "driver_id": "XE04",
        "name": "Xe 4",
        "lat": 10.7540,
        "lon": 106.6640
    },
    {
        "driver_id": "XE05",
        "name": "Xe 5",
        "lat": 10.7690,
        "lon": 106.6570
    },
    {
        "driver_id": "XE06",
        "name": "Xe 6",
        "lat": 10.7630,
        "lon": 106.6740
    },
    {
        "driver_id": "XE07",
        "name": "Xe 7",
        "lat": 10.7520,
        "lon": 106.6585
    }
]

distance_records = []

for customer in customers:
    for driver in drivers:
        distance_km = geodesic(
            (customer["lat"], customer["lon"]),
            (driver["lat"], driver["lon"])
        ).km

        distance_records.append({
            "Mã khách": customer["customer_id"],
            "Tên khách": customer["name"],
            "Mã xe": driver["driver_id"],
            "Tên xe": driver["name"],
            "Khoảng cách xe đến khách (km)": round(distance_km, 3)
        })

distance_df = pd.DataFrame(distance_records)

display(distance_df)

available_drivers = drivers.copy()
assignments = []

for customer in customers:
    best_driver = None
    best_distance = float("inf")

    for driver in available_drivers:
        distance_km = geodesic(
            (customer["lat"], customer["lon"]),
            (driver["lat"], driver["lon"])
        ).km

        if distance_km < best_distance:
            best_distance = distance_km
            best_driver = driver

    available_drivers.remove(best_driver)

    average_speed_kmh = 25
    estimated_time_min = best_distance / average_speed_kmh * 60

    assignments.append({
        "Mã khách": customer["customer_id"],
        "Tên khách": customer["name"],
        "Vĩ độ khách": customer["lat"],
        "Kinh độ khách": customer["lon"],
        "Mã xe được gán": best_driver["driver_id"],
        "Tên xe": best_driver["name"],
        "Vĩ độ xe": best_driver["lat"],
        "Kinh độ xe": best_driver["lon"],
        "Khoảng cách xe đến khách (km)": round(best_distance, 3),
        "Thời gian xe đến khách dự kiến (phút)": round(estimated_time_min, 1)
    })

assignment_df = pd.DataFrame(assignments)

display(assignment_df)

m = folium.Map(
    location=CENTER,
    zoom_start=15,
    tiles="OpenStreetMap"
)

folium.TileLayer("CartoDB positron", name="Bản đồ sáng").add_to(m)

folium.Marker(
    location=CENTER,
    popup=f"""
    <b>Mốc trung tâm</b><br>
    {center_name}<br>
    Vĩ độ: {CENTER[0]}<br>
    Kinh độ: {CENTER[1]}
    """,
    tooltip="Mốc trung tâm",
    icon=folium.Icon(color="red", icon="home")
).add_to(m)

customer_layer = folium.FeatureGroup(name="Khách hàng")
driver_layer = folium.FeatureGroup(name="Xe")
matching_layer = folium.FeatureGroup(name="Ghép xe - khách")

for customer in customers:
    folium.Marker(
        location=[customer["lat"], customer["lon"]],
        popup=f"""
        <b>{customer['customer_id']}</b><br>
        {customer['name']}<br>
        Vĩ độ: {customer['lat']}<br>
        Kinh độ: {customer['lon']}
        """,
        tooltip=customer["customer_id"],
        icon=folium.Icon(color="green", icon="user")
    ).add_to(customer_layer)

for driver in drivers:
    folium.Marker(
        location=[driver["lat"], driver["lon"]],
        popup=f"""
        <b>{driver['driver_id']}</b><br>
        {driver['name']}<br>
        Vĩ độ: {driver['lat']}<br>
        Kinh độ: {driver['lon']}
        """,
        tooltip=driver["driver_id"],
        icon=folium.Icon(color="blue", icon="car", prefix="fa")
    ).add_to(driver_layer)

for _, row in assignment_df.iterrows():
    customer_point = [row["Vĩ độ khách"], row["Kinh độ khách"]]
    driver_point = [row["Vĩ độ xe"], row["Kinh độ xe"]]

    folium.PolyLine(
        locations=[driver_point, customer_point],
        color="orange",
        weight=4,
        opacity=0.8,
        popup=f"""
        {row['Mã xe được gán']} → {row['Mã khách']}<br>
        Khoảng cách: {row['Khoảng cách xe đến khách (km)']} km<br>
        Thời gian dự kiến: {row['Thời gian xe đến khách dự kiến (phút)']} phút
        """
    ).add_to(matching_layer)

customer_layer.add_to(m)
driver_layer.add_to(m)
matching_layer.add_to(m)

folium.Circle(
    location=CENTER,
    radius=3000,
    color="red",
    fill=False,
    popup="Phạm vi mô phỏng 3 km quanh mốc trung tâm"
).add_to(m)

folium.LayerControl(collapsed=False).add_to(m)

display(m)