# -*- coding: utf-8 -*-
"""AI 23.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L5shGmJR2ycyvxFBr3khZXG1bNWxGRL_
"""

!pip install -q folium

import folium
from IPython.display import display
from geopy.distance import geodesic
CENTER_LAT = 10.761000
CENTER_LON = 106.668472
CENTER = [CENTER_LAT, CENTER_LON]

m = folium.Map(
    location=CENTER,
    zoom_start=15,
    tiles="OpenStreetMap"
)
folium.TileLayer("CartoDB positron", name="Bản đồ sáng").add_to(m)
folium.TileLayer("CartoDB dark_matter", name="Bản đồ tối").add_to(m)

center_layer = folium.FeatureGroup(name="Mốc trung tâm")
hospital_layer = folium.FeatureGroup(name="Bệnh viện")
mall_layer = folium.FeatureGroup(name="Trung tâm thương mại")
public_layer = folium.FeatureGroup(name="Địa điểm công cộng")
transport_layer = folium.FeatureGroup(name="Giao thông")

folium.Marker(
    location=CENTER,
    popup="""
    <b>Mốc trung tâm</b><br>
    QM69+95 Diên Hồng, Hồ Chí Minh, Việt Nam<br>
    Vĩ độ: 10.761000<br>
    Kinh độ: 106.668472
    """,
    tooltip="Mốc trung tâm",
    icon=folium.Icon(color="red", icon="home")
).add_to(center_layer)

places = [
    {
        "name": "Sân vận động Thống Nhất",
        "type": "Địa điểm công cộng",
        "lat": 10.7609,
        "lon": 106.6622,
        "desc": "Sân vận động lớn tại Quận 10, dùng cho các hoạt động thể thao và sự kiện."
    },
    {
        "name": "Vạn Hạnh Mall",
        "type": "Trung tâm thương mại",
        "lat": 10.7712,
        "lon": 106.6706,
        "desc": "Trung tâm thương mại, mua sắm, ăn uống và giải trí."
    },
    {
        "name": "Bệnh viện Chợ Rẫy",
        "type": "Bệnh viện",
        "lat": 10.7578,
        "lon": 106.6594,
        "desc": "Một trong những bệnh viện lớn tại TP.HCM."
    },
    {
        "name": "Nhà thi đấu Phú Thọ",
        "type": "Địa điểm công cộng",
        "lat": 10.7624,
        "lon": 106.6542,
        "desc": "Khu nhà thi đấu phục vụ thể thao, sự kiện và hoạt động cộng đồng."
    },
    {
        "name": "Công viên Lê Thị Riêng",
        "type": "Địa điểm công cộng",
        "lat": 10.7825,
        "lon": 106.6674,
        "desc": "Công viên công cộng phục vụ vui chơi, giải trí và sinh hoạt ngoài trời."
    },
    {
        "name": "Ga Sài Gòn",
        "type": "Giao thông",
        "lat": 10.7827,
        "lon": 106.6779,
        "desc": "Nhà ga đường sắt quan trọng tại TP.HCM."
    }
]

for place in places:
    popup_text = f"""
    <b>{place['name']}</b><br>
    Loại: {place['type']}<br>
    Mô tả: {place['desc']}<br>
    Vĩ độ: {place['lat']}<br>
    Kinh độ: {place['lon']}
    """

    if place["type"] == "Bệnh viện":
        icon = folium.Icon(color="blue", icon="plus-sign")
        layer = hospital_layer
    elif place["type"] == "Trung tâm thương mại":
        icon = folium.Icon(color="green", icon="shopping-cart")
        layer = mall_layer
    elif place["type"] == "Giao thông":
        icon = folium.Icon(color="purple", icon="road")
        layer = transport_layer
    else:
        icon = folium.Icon(color="orange", icon="info-sign")
        layer = public_layer

    folium.Marker(
        location=[place["lat"], place["lon"]],
        popup=popup_text,
        tooltip=place["name"],
        icon=icon
    ).add_to(layer)

center_layer.add_to(m)
hospital_layer.add_to(m)
mall_layer.add_to(m)
public_layer.add_to(m)
transport_layer.add_to(m)

folium.Circle(
    location=CENTER,
    radius=1000,
    popup="Vùng bán kính 1 km quanh mốc trung tâm",
    color="red",
    fill=True,
    fill_opacity=0.1
).add_to(m)

folium.LayerControl(collapsed=False).add_to(m)

display(m)